esphome:
  name: dht22-gughan-room
  platform: ESP8266
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_pswd

ota:
  password: !secret ota_pswd

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pswd

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dht22-Gughan-Room"
    password: !secret ap_pswd

captive_portal:

web_server:
  port: 80

sensor:
  - platform: dht
    model: "DHT22"
    pin: D2
    temperature:
      name: "Gughan Room Temperature"
      id: "gughan_room_temperature"
      unit_of_measurement: "°C"
    humidity:
      name: "Gughan Room Humidity"
      id: "gughan_room_humidity"
      unit_of_measurement: "%"
    update_interval: 2s
  - platform: template
    name: "Gughan Room Heat Index"
    id: "gughan_room_heat_index"
    unit_of_measurement: "°C"
    lambda: return -8.78469475556 + (1.61139411 * id(gughan_room_temperature).state) + (2.33854883889 * id(gughan_room_humidity).state) + (-0.14611605 * id(gughan_room_temperature).state * id(gughan_room_humidity).state) + (-0.012308094 * pow(id(gughan_room_temperature).state, 2)) + (-0.0164248277778 * pow(id(gughan_room_humidity).state, 2)) + (0.002211732 * pow(id(gughan_room_temperature).state, 2) * id(gughan_room_humidity).state) + (0.00072546 * id(gughan_room_temperature).state * pow(id(gughan_room_humidity).state, 2)) + (-0.000003582 * pow(id(gughan_room_temperature).state, 2) * pow(id(gughan_room_humidity).state, 2));
    update_interval: 2s
    