substitutions:
  device_name: gughan_room_bathroom_sdr3
  device_hostname: gughan-room-bathroom-sdr3
  long_device_name: Gughan Room Bathroom SDR3

external_components:
  - source: github://berfenger/esphome_components
    components: [ cse7761 ]
    
esphome:
  name: ${device_hostname}
  platform: ESP32
  board: esp32dev

# Enable logging
logger:
  baud_rate: 0

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_pswd
    hidden: false
  manual_ip:
    gateway: 192.168.0.1
    subnet: 255.255.255.0
    static_ip: 192.168.0.199
  domain: .local
  power_save_mode: light
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${long_device_name} AP"
    password: !secret ap_pswd

captive_portal:

# Enable Web server
web_server:
  port: 80

# Enable Home Assistant API
api:
  password: !secret api_pswd

# Enable Over The Air update
ota:
  password: !secret ota_pswd

# enable ble tracking
esp32_ble_tracker:

time:
  - platform: homeassistant
    id: homeassistant_time

# uart:
#   rx_pin: RX
#   baud_rate: 4800

sensor:
  # - platform: cse7766  #The actual chip on the DualR3 is a CSE7761, no driver available yet!
  #   update_interval: 5s
  #   current:
  #     name: "$long_device_name Current"
  #   voltage:
  #     name: "$long_device_name Voltage"
  #   power:
  #     name: "$long_device_name Power"
  #     id: power
  #     on_value_range:
  #       - above: 1.0
  #         then:
  #           - logger.log: "$long_device_name Power above 1.0A"
  #       - below: 1.0
  #         then:
  #           - logger.log: "$long_device_name Power below 1.0A"
  # Extra sensor to keep track of plug uptime
  - platform: uptime
    name: ${long_device_name} Uptime Sensor
    filters:
      - lambda: return x / 3600;
    unit_of_measurement: "hours"
    accuracy_decimals: 2
  # Extra sensor for WiFi signal
  - platform: wifi_signal
    name: ${long_device_name} WiFi RSSI
    update_interval: 60s

  - platform: cse7761
    update_interval: 5s
    voltage:
      name: ${long_device_name} CSE7761 Voltage
    current_1:
      name: ${long_device_name} CSE7761 Current Light
    current_2:
      name: ${long_device_name} CSE7761 Current Fan
    active_power_1:
      name: ${long_device_name} CSE7761 Active Power Light
    active_power_2:
      name: ${long_device_name} CSE7761 Active Power Fan

# cse7761 uart port
uart:
  tx_pin: GPIO25
  rx_pin: GPIO26
  baud_rate: 38400
  parity: EVEN
  stop_bits: 1

status_led:
  pin:
    number: GPIO13
    inverted: true

output:
  - platform: gpio
    id: ${device_name}_relay_1
    pin: GPIO27
  - platform: gpio
    id: ${device_name}_relay_2
    pin: GPIO14

switch:
  - platform: output
    id: ${device_name}_switch_light
    name: ${long_device_name} Switch Light
    output: ${device_name}_relay_1
  - platform: output
    id: ${device_name}_switch_fan
    name: ${long_device_name} Switch Fan 
    output: ${device_name}_relay_2

binary_sensor:
  - platform: gpio
    name: Cover Button
    pin: GPIO00
    id: reset
    internal: true
    filters:
      - invert:
      - delayed_off: 10ms
    on_click:
      min_length: 150ms
      max_length: 500ms
      then:
        - switch.toggle: 
            id: ${device_name}_switch_light
    on_double_click:
      - switch.toggle: 
          id: ${device_name}_switch_fan
  - platform: gpio
    pin:
      number: GPIO32
      mode: INPUT_PULLUP
      inverted: True
    name: ${long_device_name} Switch Input Light
    on_state:
      then:
        - switch.toggle:
            id: ${device_name}_switch_light
  - platform: gpio
    pin:
      number: GPIO33
      mode: INPUT_PULLUP
      inverted: True
    name: ${long_device_name} Switch Input Fan
    on_state:
      then:
        - switch.toggle:
            id: ${device_name}_switch_fan
