substitutions:
  device_name: portico_lights_smr2
  long_device_name: Portico Light SMR2

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp8285

wifi:
  networks:
  - ssid: !secret wifi_ext_ssid
    password: !secret wifi_pswd
    hidden: false
  manual_ip:
    gateway: 192.168.0.1
    subnet: 255.255.255.0
    static_ip: 192.168.0.40
  domain: .local

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${long_device_name} AP"
    password: !secret ap_pswd

captive_portal:

# Enable logging
logger:

# Enable Web server
web_server:
  port: 80

# Enable Home Assistant API
api:
  password: !secret api_pswd

# Enable Over The Air update
ota:
  password: !secret ota_pswd

time:
  - platform: homeassistant
    id: homeassistant_time
    on_time:
      - seconds: 0
        minutes: 0
        hours: 6
        then:
          - switch.turn_off:
              id: ${device_name}_switch
      - seconds: 0
        minutes: 0
        hours: 18
        then:
          - switch.turn_on:
              id: ${device_name}_switch

sensor:
# Extra sensor to keep track of plug uptime
  - platform: uptime
    name: ${long_device_name} Uptime Sensor
    filters:
      - lambda: return x / 3600;
    unit_of_measurement: "hours"
    accuracy_decimals: 2

# Extra sensor for WiFi signal
  - platform: wifi_signal
    name: ${long_device_name} WiFi RSSI
    update_interval: 60s

status_led:
  pin:
    number: GPIO13
    inverted: true

output:
  - platform: gpio
    id: ${device_name}_relay
    pin: GPIO12

switch:
  - platform: output
    id: ${device_name}_switch
    name: ${long_device_name} Switch
    output: ${device_name}_relay

binary_sensor:
  - platform: gpio
    pin: GPIO00
    id: reset
    internal: true
    filters:
      - invert:
      - delayed_off: 10ms
    on_press:
      - switch.toggle: 
          id: ${device_name}_switch

  - platform: gpio
    name: ${long_device_name} Switch Input
    pin: GPIO04
    id: ${device_name}_switch_input
    on_press:
      then:
        - switch.toggle:
            id: ${device_name}_switch