substitutions:
  device_name: sonoff_mini_r2_test

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp8285

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_pswd
    hidden: false
  manual_ip:
    gateway: 192.168.0.1
    subnet: 255.255.255.0
    static_ip: 192.168.0.40
  domain: .local

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name}_Hotspot"
    password: !secret ap_pswd

captive_portal:

# Enable logging
logger:

# Enable Web server
web_server:
  port: 80

# Enable Home Assistant API
api:
  password: !secret api_pswd

# Enable Over The Air update
ota:
  password: !secret ota_pswd

time:
  - platform: homeassistant
    id: homeassistant_time

sensor:
# Extra sensor to keep track of plug uptime
  - platform: uptime
    name: ${device_name}_Uptime Sensor
    filters:
      - lambda: return x / 3600;
    unit_of_measurement: "hours"
    accuracy_decimals: 2

# Extra sensor for WiFi signal
  - platform: wifi_signal
    name: ${device_name}_WiFi Sensor
    update_interval: 60s

status_led:
  pin:
    number: GPIO13
    inverted: true

output:
  - platform: gpio
    id: ${device_name}_relay_1
    pin: GPIO12

light:
  - platform: binary
    id: ${device_name}_light_1
    name: ${device_name}_Lights
    output: ${device_name}_relay_1    

binary_sensor:
  - platform: gpio
    pin: GPIO00
    id: reset
    internal: true
    filters:
      - invert:
      - delayed_off: 10ms
    on_press:
      - light.toggle: 
          id: ${device_name}_light_1

  - platform: gpio
    name: ${device_name}_Lights
    pin: GPIO04
    id: ${device_name}_switch_1
    on_press:
      then:
#        - switch.turn_on:
        - light.toggle: 
            id: ${device_name}_light_1
    on_release:
      then:
#        - switch.turn_off:
        - light.toggle: 
            id: ${device_name}_light_1