light:
  - platform: group
    name: Gughan Room Lights
    entities:
      - light.gughan_room_window_bulb
      - light.gughan_room_workshop_bulb
      - light.gughan_room_tubelight

climate:
  - platform: smartir
    name: Gughan Room AC
    unique_id: gughan_room_mitsubishi_ac
    device_code: 1681
    controller_data: remote.gughan_room_remote
    temperature_sensor: sensor.gughan_room_temperature
    humidity_sensor: sensor.gughan_room_humidity
    # power_sensor: binary_sensor.ac_power

automation:
  - id: sunrise_wakeup_alarm
    alias: Sunrise light alarm
    description: "Simulate sunrise on the window bulb when I'm home and my alarm rings"
    trigger:
      - platform: time
        at: sensor.mi_a1_next_alarm
    condition:
      - condition: state
        entity_id: person.gughan_ravikumar
        state: home
    action:
      - service: light.turn_on
        entity_id: light.gughan_room_window_bulb
        data:
          color_temp: 370
          brightness_pct: 10
      - service: script.turn_on
        entity_id: script.fade_light
        data:
          variables:
            light_entity: light.gughan_room_window_bulb
            duration:
              hours: 1
              minutes: 30
              seconds: 0
            change_pct: 1

  # Add conditions to exclude songs
  # Make this work for generic media players and groups of people
  - id: lights_off_media_start
    alias: Turn off light when media starts playing
    trigger:
      platform: state
      entity_id: media_player.jellyfin_gl65
      from: idle
      to: playing
    condition:
      - condition: state
        entity_id: person.gughan_ravikumar
        state: home
    action:
      - service: scene.create
        data:
          scene_id: before_media_play
          snapshot_entities:
            - light.gughan_room_window_bulb
            - light.gughan_room_workshop_bulb
            - light.gughan_room_tubelight
      - service: light.turn_off
        entity_id: light.gughan_room_lights

  - id: lights_on_media_pause
    alias: Turn on light when media is paused
    trigger:
      platform: state
      entity_id: media_player.jellyfin_gl65
      from: playing
      to: paused
    condition:
      - condition: state
        entity_id: person.gughan_ravikumar
        state: home
    action:
      - service: light.turn_on
        entity_id: light.gughan_room_window_bulb
        data:
          brightness: 25
          color_temp: 370

  - id: lights_off_media_play
    alias: Turn off light when media is played
    trigger:
      platform: state
      entity_id: media_player.jellyfin_gl65
      from: paused
      to: playing
    condition:
      - condition: state
        entity_id: person.gughan_ravikumar
        state: home
    action:
      - service: light.turn_off
        entity_id: light.gughan_room_lights

  - id: lights_on_media_end
    alias: Go back to normal when media ends
    trigger:
      # to avoid triggering from unknown to idle
      - platform: state
        entity_id: media_player.jellyfin_gl65
        from: playing
        to: idle
      - platform: state
        entity_id: media_player.jellyfin_gl65
        from: paused
        to: idle
    condition:
      - condition: state
        entity_id: person.gughan_ravikumar
        state: home
    action:
      - service: scene.turn_on
        target:
          entity_id: scene.before_media_play

  - id: lights_off_nobody
    alias: Turn lights off when nobody is detected
    trigger:
      # no movement inside the romm for 30 minutes
      - platform: state
        entity_id: binary_sensor.gughan_room_motion_sensor
        to: "off"
        for:
          minutes: 30
    action:
      service: light.turn_off
      entity_id: light.gughan_room_lights

  # This is pointless cuz the Tuya motion sensor I have responds after 10 seconds
  # - id: lights_on_motion_detect
  #   alias: Turn lights on when motion is detected
  #   trigger:
  #     - platform: state
  #       entity_id: binary_sensor.gughan_room_motion_sensor
  #       to: "on"
  #   condition:
  #     # only during daytime
  #     - condition: time
  #       after: "07:00:00"
  #       before: "21:00:00"
  #     # no light is already turned on
  #     - condition: state
  #       entity_id:
  #         - light.gughan_room_tubelight
  #         - light.gughan_room_window_bulb
  #         - light.gughan_room_workshop_bulb
  #       state: "off"
  #   action:
  #     - service: light.turn_on
  #       entity_id: light.gughan_room_tubelight

  # - id: cool_when_room_too_hot
  #   this is pointless
  #   room doesn't stay cold for more than 10 mins
  #   alias: Cool the room when it gets too hot
  #   trigger:
  #     - platform: template
  #       value_template: "{{ states('sensor.gughan_room_heat_index') | int > 30 }}"
  #       for:
  #         minutes: 5
  #   action:
  #     - service: climate.turn_on
  #       target:
  #         entity_id: climate.gughan_room_ac
  #     - delay:
  #         minutes: 15
  #     - service: climate.turn_off
  #       target:
  #         entity_id: climate.gughan_room_ac

  # convert physical switch change to light change
  - id: gughan_room_main_light_switch
    alias: Sync State Gughan Room Main Light
    description: ""
    mode: restart
    max_exceeded: silent
    trigger:
      - platform: state
        entity_id: binary_sensor.gughan_room_main_light_switch_input
    action:
      - service: light.toggle
        data:
          entity_id: light.gughan_room_tubelight

  - id: gughan_room_workshop_light_switch
    alias: Sync State Gughan Room Workshop Light
    description: ""
    mode: restart
    max_exceeded: silent
    trigger:
      - platform: state
        entity_id: binary_sensor.gughan_room_workshop_light_switch_input
    action:
      - service: light.toggle
        data:
          entity_id: light.gughan_room_workshop_bulb

  - id: gughan_room_window_light_switch
    alias: Sync State Gughan Room Window Light
    description: ""
    mode: restart
    max_exceeded: silent
    trigger:
      - platform: state
        entity_id: binary_sensor.gughan_room_window_light_switch_input
    action:
      - service: light.toggle
        data:
          entity_id: light.gughan_room_window_bulb
