binary_sensor:
  - platform: ping
    host: 1.1.1.1
    count: 5
    scan_interval: 5
    name: "Internet Status"
#
# device_tracker:
#   Deprecated
#   - platform: nmap_tracker
#     hosts: 192.168.0.0/24
#     home_interval: 10
#     exclude:
#       - 192.168.0.11
#       - 192.168.0.12
#       - 192.168.0.13
#       - 192.168.0.14
#       - 192.168.0.15
#       - 192.168.0.31
#       - 192.168.0.32
#       - 192.168.0.33
#       - 192.168.0.99
#       - 192.168.0.100
#       - 192.168.0.101
#       - 192.168.0.111

automation:
  - id: speedtest
    alias: Call speed test when speed unavailable
    trigger:
      - platform: state
        entity_id:
          - sensor.speedtest_download
          - sensor.speedtest_upload
          - sensor.speedtest_ping
        to: unavailable
        for:
          minutes: 5
    condition:
      - condition: state
        entity_id: binary_sensor.internet_status
        state: "on"
    action:
      - service: speedtestdotnet.speedtest
